functionsDirectory = "C:\\Users\\筑後サポステオンライン\\Desktop\\DMMO-RPG YGGDRASIL-ユグドラシル-\\知識領域\\現実世界\\FVSR導入セミナー\\v10-設計中\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\Users\\筑後サポステオンライン\\Desktop\\DMMO-RPG YGGDRASIL-ユグドラシル-\\知識領域\\現実世界\\FVSR導入セミナー\\v10-設計中"
publishOrigin = "config"
functions = "C:\\Users\\筑後サポステオンライン\\Desktop\\DMMO-RPG YGGDRASIL-ユグドラシル-\\知識領域\\現実世界\\FVSR導入セミナー\\v10-設計中\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"